The waifu searcher now saves the urls so the list will remain the same after the app has been restarted.
Error: There are still times when pressing the search button will invoke an outofbounds exception in the random method in the Anime Class